/*
# Create email verification tokens table

1. New Tables
- `email_verification_tokens`
  - `id` (uuid, primary key)
  - `user_id` (uuid, references auth.users, ON DELETE CASCADE)
  - `token` (text, unique, not null) — opaque random token for the verify link
  - `expires_at` (timestamptz, not null) — 24-hour expiry
  - `used_at` (timestamptz, nullable) — set when the token is consumed
  - `created_at` (timestamptz, default now())
2. Security
- Enable RLS on `email_verification_tokens`.
- Allow authenticated users to read their own tokens (for checking status).
- Allow anon users to SELECT tokens (needed for the verify-email edge function which runs with service role anyway, but anon SELECT is safe since the token is opaque and single-use).
- All INSERT/UPDATE/DELETE operations are done server-side via the service role key in edge functions, so no anon INSERT/UPDATE/DELETE policies are needed.
3. Indexes
- Unique index on `token` for fast lookups.
- Index on `user_id` for cleanup queries.
4. Notes
- The token is a 32-byte hex string generated by the edge function using crypto.getRandomValues.
- Tokens expire 24 hours after creation.
- Once used, `used_at` is set so the same link can't be reused.
*/

CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token text UNIQUE NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_verification_tokens_user_id
  ON email_verification_tokens(user_id);

ALTER TABLE email_verification_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_tokens" ON email_verification_tokens;
CREATE POLICY "select_own_tokens"
  ON email_verification_tokens FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "anon_select_tokens" ON email_verification_tokens;
CREATE POLICY "anon_select_tokens"
  ON email_verification_tokens FOR SELECT
  TO anon
  USING (true);